Work on a few issues...
ioBroker/ioBroker.s7 pull request #105
Opened 2022-02-06 18:14 UTC by jogibear9988

I've started to work on a few issues, but not yet found time to test against real s7

2022-02-06 18:17 UTC, jogibear9988 commented
maybe the byte order in s5time could be wrong...

2022-02-13 23:23 UTC, Apollon77 requested changes

2022-02-13 23:23 UTC, Apollon77 commented on main.js
> +        case 'DWORD':
DWORD is there twice

2022-02-13 23:23 UTC, Apollon77 commented on main.js
> +        case 'DWORD':
Copy paste error? STRING, ARRA and S7STRING missing

2022-02-13 23:23 UTC, Apollon77 commented on main.js
> +        case 'DWORD':
should be S7TIME?

2022-02-13 23:23 UTC, Apollon77 commented on main.js
> +        if (main.acp.connectionType) {
Where this is coming from? there is no config option for this or?!

2022-04-03 14:22 UTC, merged

2022-04-03 16:07 UTC, Apollon77 commented
@GermanBluefox This was not a good idea unless you want to fix now all tghe issues introduced by this PR :-(( See my comments ... there are several things completely unclear with the PR

2022-04-03 16:09 UTC, Apollon77 commented
Ok seem some fixes were done, but https://github.com/ioBroker/ioBroker.s7/blob/master/main.js#L1053 is still in ...

2022-04-03 18:17 UTC, jogibear9988 commented
Never saw the comments...
The connectionType has no UI but you can modify via objects.
Most people 99% normaly don't need it.

And no it is S5Time not S7Time

2022-04-03 20:39 UTC, Apollon77 commented
>  The connectionType has no UI but you can modify via objects.

Undocumented settings ? Without a Code comment for the purpose and why it is undocumented setting and for what to use it OR Readme  info as "expert stuff" OR anything else that helps understand it, it will be seen by any developer (including you maybe in a year) as wrong and buggy code. my opinion about it.

Then please have a look at the fixes @GermanBluefox did today and check if he fixed anything correctly and create a PR if not because it is already released now :-(

2022-04-03 21:01 UTC, jogibear9988 commented
I looked at the fixes from BlueFox, they look good atm.

Problem is, there is a S7Time defined in the Code, but on PLC Side the type meant is "DATE_AND_TIME"
But if we rename it, it would be a breaking change

There are also more types missing like "Time", "Time_Of_Day", ....
Or newer ones from 1500 PLCs like LReal, LInt,...

2022-04-03 21:14 UTC, Apollon77 commented
Can you please provide a PR with some code comments for that undocumented option please that we at least have infos in code? Thank you

2022-04-04 08:46 UTC, jogibear9988 commented
What infos do you want? It's only one line of code, wich uses the value from the settings to call the api from snap7.
Should we list the constants?

0x01 = PG connection
0x02 = OP connection
0x03 = Other connection
0xFD = S7 Basic connection

2022-04-04 09:50 UTC, Apollon77 commented
I would like to see something helpful that describes why this code part https://github.com/ioBroker/ioBroker.s7/blob/master/main.js#L1053 exists and in which cases the user can use this for what. Somethig that describes other developers what this special code does and why it is there.

```
// Use this unofficial parameter to set the Connection type if you need a different one then the default (**Add what default is**)
```

Yes also the allowed values, or maybe a link to the snap7 specs for it, can also help

But effectively ... I still do not understand why we need an unofficial parameter here and not simply add it correctly as an adapter parameter ...